version: '3'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: codebounty
      POSTGRES_PASSWORD: password
      POSTGRES_DB: codebounty
    ports:
      - "5432:5432"
